Fix error in running of command in command logging

diff --git a/rsnapshot-herder b/rsnapshot-herder
--- a/rsnapshot-herder
+++ b/rsnapshot-herder
@@ -14,7 +14,6 @@ if [ ! -d "$rsnapshot_root" ]; then printf "ERROR: \"$rsnapshot_root\" does not 
 
 rsnapshot_lockfile="`( egrep '^lockfile' "$rsnapshot_conf" ; echo $? > $cmd_exit_value_tmp ) | cut -f 2`"
 if [ `cat $cmd_exit_value_tmp` -ne 0 ]; then printf "ERROR: 'lockfile' is not defined in \"$rsnapshot_conf\"\n" 1>&2; exit 1; fi
-echo $rsnapshot_lockfile
 
 rsnapshot_logfile="`egrep '^logfile' "$rsnapshot_conf" | cut -f 2`"
 completed_or_error=0
@@ -71,8 +70,10 @@ log_msg() {
 		if [ "$LOG_OUTPUT" = "stdout" ]; then
 			printf "$time$script_name $message"
 		elif [ -z "$rsnapshot_logfile" ]; then
+			echo "Output to logger"
 			printf "$time$script_name $rsnapshot_conf $message" | logger
 		else
+			echo "Output to log file"
 			printf "$time$script_name $message" >> "$rsnapshot_logfile"
 		fi
 	fi
@@ -95,16 +96,11 @@ log_cmd() {
 	cmd="$@"
 
 	time="$(date +'%d-%m-%Y %T') "
-	if [ $log_value -le $LOG_LEVEL ]; then
-		if [ "$LOG_OUTPUT" = "stdout" -o $mail_value -le $MAIL_LEVEL ]; then
-			if [ $mail_value -le $MAIL_LEVEL ]; then
-				( printf "$time\n" ; eval "$cmd" 2>&1 ; echo $? > $cmd_exit_value_tmp ) | tee -a $mail_message
-			else
-				printf "$time\n" ; eval "$cmd" 2>&1 ; echo $? > $cmd_exit_value_tmp
-			fi
-		fi
+	# rsnapshot outputs to the log automatically, so only need to handle the MAIL_LEVEL
+	if [ $mail_value -le $MAIL_LEVEL ]; then
+		( printf "$time\n" ; eval "$cmd" 2>&1 ; echo $? > $cmd_exit_value_tmp ) | tee -a $mail_message
 	else
-		eval "$cmd" 2>&1 ; echo $? > $cmd_exit_value_tmp
+		printf "$time\n" ; eval "$cmd" 2>&1 ; echo $? > $cmd_exit_value_tmp
 	fi
 
 	cmd_exit=`cat $cmd_exit_value_tmp`
@@ -145,7 +141,6 @@ exit_value_file="$state_dir/exit-value"
 backup_time_file="$state_dir/backup_time"
 n_failures_file="$state_dir/n_failures"
 n_runnings_file="$state_dir/n_runnings"
-n_timeouts_file="$state_dir/n_timeouts"
 fastest_rotation_file="$state_dir/fastest_rotation"
 
 # Create state directory if it does not exist
@@ -178,9 +173,6 @@ if [ ! -f "$n_failures_file" ]; then echo 0 > "$n_failures_file"; fi
 # If n_runnings file does not exist, then create it
 if [ ! -f "$n_runnings_file" ]; then echo 0 > "$n_runnings_file"; fi
 
-# If n_timeouts file does not exist, then create it
-if [ ! -f "$n_timeouts_file" ]; then echo 0 > "$n_timeouts_file"; fi
-
 # If fastest_rotation file does not exist, then create it
 if [ ! -f "$fastest_rotation_file" ]; then echo 0 > "$fastest_rotation_file"; fi
 previous_fastest_rotation=`cat "$fastest_rotation_file"`
@@ -199,7 +191,6 @@ if [ $previous_exit_value -ne 0 -a $previous_exit_value -ne 2 -o $backup_time_de
 		log_msg 2 2 "Previous 'rsnapshot sync' incomplete, so re-try...\n"
 	fi
 
-	timeout=0
 	if [ ! -f "$rsnapshot_lockfile" ]; then
 		running=-1
 	else
@@ -221,30 +212,21 @@ if [ $previous_exit_value -ne 0 -a $previous_exit_value -ne 2 -o $backup_time_de
 			n_runnings=$((`cat "$n_runnings_file"` + 1))
 			echo $n_runnings > "$n_runnings_file"
 			log_msg 2 3 "Skipped sync because rsnapshot is already running for this client\n"
-		# If the ssh connection timedout
-		elif [ $timeout -eq 1 ]
-		then
-			n_timeouts=$((`cat "$n_timeouts_file"` + 1))
-			echo $n_timeouts > "$n_timeouts_file"
-			echo "Connection to source timed out"
 		else
 			n_failures=`cat "$n_failures_file"`
 			n_failures=$((n_failures + 1))
 			echo $n_failures > "$n_failures_file"
 			if [ $backup_time_delta -ge $(( FAIL_WARNING * FASTEST_ROTATION )) ]; then
-				log_msg 0 0 "ERROR: Backup has failed to complete $n_failures times\n"
+				log_msg 0 0 "ERROR: '${delta_names[1]}' backup has failed to complete $n_failures times\n"
 				completed_or_error=1
 			fi
 		fi
-		
-		# Handle when ssh timeouts
 	else
 		log_msg 1 1 "rsnapshot sync completed OK\n"
 		# Save time of rsnapshot
 		echo $((`date "+%s"` / 60 )) > "$backup_time_file"
 		echo 0 > "$n_failures_file"
 		echo 0 > "$n_runnings_file"
-		echo 0 > "$n_timeouts_file"
 		completed_or_error=1
 	fi
 
